name: Public Preview Builds

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  publish-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Build
      run: dotnet build -c Release -p:SymbolPackageFormat=symbols.nupkg -p:ContinuousIntegrationBuild=true
    - name: Publish
      run: dotnet nuget push src/Xdg.Directories/bin/Release/*.symbols.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://git.froth.zone/api/packages/mirrors/nuget/index.json